#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 Red Hat, Inc. <sd-mt-sre@redhat.com>
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

export PROJECT_ROOT="${PWD}"
export DEPENDENCY_DIR="${PROJECT_ROOT}/.cache/dependencies"
export MAGEFILE_CACHE="${PROJECT_ROOT}/.cache/magefile"
export GOFLAGS=""

if [ ! -f "bin/mage" ]; then
  go build -o bin/mage ./cmd/mage
fi

exec ./bin/mage -v "$@"
